import * as http from 'https';
import {request} from "https";
import {argv} from 'yargs';
import {Observable} from "rxjs/Observable";
import {of} from "rxjs/observable/of";
import {delay} from "rxjs/operator/delay";
import {pipeFromArray} from "rxjs/util/pipe";
import {map} from "rxjs/operator/map";
import {from} from "rxjs/observable/from";
import {RequestOptions} from "https";
import {ServerOptions} from "https";
